- name: Install Apache
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Apache
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start and enable Apache
      service:
        name: "{{ 'apache2' if ansible_os_family == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes

    - name: Configure Firewall to allow HTTP and HTTPS
      firewalld:
        service: 
          - http
          - https
        permanent: yes
        state: enabled
        immediate: yes
      when: ansible_os_family == "RedHat"

    - name: Configure UFW to allow HTTP and HTTPS
      ufw:
        rule: allow
        name: "{{ item }}"
        state: enabled
      loop:
        - 'Apache'
        - 'OpenSSH'
      when: ansible_os_family == "Debian"

    - name: Create a simple index.html
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
            <head>
              <title>Welcome to Apache</title>
            </head>
            <body>
              <h1>Apache is successfully installed!</h1>
            </body>
          </html>